spring:
  application:
    name: pupuAdmin
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://43.142.173.112:3306/pupu?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9991
  tomcat:
    uri-encoding: UTF-8

redis:
  # develop
  host:
  # preview
  #    host:
  port: 6379
  timeout: 5000
  jedis:
    pool:
      max-idle: 25
      min-idle: 10
      max-active: 50
      max-wait: -1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9990/eureka/
  instance:
    prefer-ip-address: true

